version: '2'
services:
  nginx:
    container_name: nginx
    image: nginx:1.11.1-alpine
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
    ports:
      - 80:80
    links:
      - web
      - phpmyadmin
    networks:
      app_net:
        ipv4_address: 172.16.238.10
    dns:
      - 8.8.8.8
      - 8.8.4.4
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    environment:
      #MYAPP_DATABASE_USERNAME: $MYAPP_DATABASE_USERNAME
      #MYAPP_DATABASE_PASSWORD: $MYAPP_DATABASE_PASSWORD
      MYAPP_DATABASE_URL: "mysql2://${MYAPP_DATABASE_USERNAME}:${MYAPP_DATABASE_PASSWORD}@db:3306"
      #MYAPP_SLACK_API_TOKEN: $MYAPP_SLACK_API_TOKEN
  web:
    container_name: web
    extends:
      service: app
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./rails/src:/myapp
    #ports:
    #  - "3000:3000"
    links:
      - db
      - redis
    networks:
      app_net:
        ipv4_address: 172.16.238.20
  redis:
    container_name: redis
    image: redis:3.2.6-alpine
    networks:
      app_net:
        ipv4_address: 172.16.238.30
  db:
    container_name: db
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: $MYAPP_DATABASE_PASSWORD
    volumes:
      - db-data:/var/lib/mysql
    networks:
      app_net:
        ipv4_address: 172.16.238.40

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8080:80
    links:
      - db
    environment:
     - PMA_ARBITRARY=1
    restart: always
    networks:
      app_net:
        ipv4_address: 172.16.238.50

volumes:
  db-data:
    driver: local

networks:
  app_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
        gateway: 172.16.238.1