FROM ruby:2.4.0-alpine
ENV LANG ja_JP.UTF-8
ENV RAILS_ENV production
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs
RUN mkdir /myapp
WORKDIR /myapp
ADD ./rails/src /myapp
RUN bundle install --jobs 20 --retry 5 --without development test
#RUN bundle exec rake tmp:create
#RUN bundle exec rake assets:precompile