version: '2'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: $MYAPP_DATABASE_PASSWORD
    volumes:
      - db-data:/var/lib/mysql
  redis:
    image: redis
  app:
    build: .
    environment:
      MYAPP_DATABASE_USERNAME: root
      MYAPP_DATABASE_PASSWORD: $MYAPP_DATABASE_PASSWORD
      MYAPP_DATABASE_HOST: db
      MYAPP_SLACK_API_TOKEN: $MYAPP_SLACK_API_TOKEN
  web:
    extends:
      service: app
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./rails/src:/myapp
    ports:
      - "3000:3000"
    links:
      - db
      - redis

volumes:
  db-data:
    driver: local